In [1]:
import numpy as np
import pandas as pd

In [3]:
#1.
arr1=np.arange(1, 11)
reshaped_arr1=arr1.reshape(2, 5)
print("Exercise 1:\n",reshaped_arr1)

Exercise 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
#2.
arr2=np.arange(1, 21)
sliced_arr2=arr2[5:16]
print("\nExercise 2:\n",sliced_arr2)


Exercise 2:
 [ 6  7  8  9 10 11 12 13 14 15 16]


In [7]:
#3.
fruit_series=pd.Series({'apples':3,'bananas':2,'oranges':1})
fruit_series['pears']=4
print("\nExercise 3:\n",fruit_series)


Exercise 3:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [9]:
#4.
data = {
    'name':['Alice','Bob','Charlie','David','Eva','Frank','Grace','Hannah','Ian','Jane'],
    'age':[25,32,29,45,22,36,41,28,33,30],
    'gender':['F','M','M','M','F','M','F','F','M','F']
}
df=pd.DataFrame(data)
print("\nExercise 4:\n",df)


Exercise 4:
       name  age gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   29      M
3    David   45      M
4      Eva   22      F
5    Frank   36      M
6    Grace   41      F
7   Hannah   28      F
8      Ian   33      M
9     Jane   30      F


In [13]:
#5.
occupations=['Programmer','Manager','Analyst','Manager','Analyst','Programmer','Manager','Analyst','Programmer','Manager']
df['occupation']=occupations
print("\nExercise 5:\n",df)


Exercise 5:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   29      M     Analyst
3    David   45      M     Manager
4      Eva   22      F     Analyst
5    Frank   36      M  Programmer
6    Grace   41      F     Manager
7   Hannah   28      F     Analyst
8      Ian   33      M  Programmer
9     Jane   30      F     Manager


In [19]:
#6.
age_filtered_df=df[df['age']>=30]
print("\nExercise 6:\n",age_filtered_df)


Exercise 6:
     name  age gender  occupation
1    Bob   32      M     Manager
3  David   45      M     Manager
5  Frank   36      M  Programmer
6  Grace   41      F     Manager
8    Ian   33      M  Programmer
9   Jane   30      F     Manager


In [21]:
#7.
csv_file="dataframe_output.csv"
df.to_csv(csv_file,index=False)
df_from_csv=pd.read_csv(csv_file)
print("\nExercise 7:\n",df_from_csv)


Exercise 7:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   29      M     Analyst
3    David   45      M     Manager
4      Eva   22      F     Analyst
5    Frank   36      M  Programmer
6    Grace   41      F     Manager
7   Hannah   28      F     Analyst
8      Ian   33      M  Programmer
9     Jane   30      F     Manager
